version: '3.8'

services:
  ai:
    build:
      context: ./WealthWise.AI
      dockerfile: Dockerfile
    image: wealthwise-ai:local
    ports:
      - "8000:8000"
    restart: unless-stopped

  api:
    build:
      context: ./WealthWise.API
    image: wealthwise-api:local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AI_SERVICE_URL=http://ai:8000
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=WealthWiseDb;User Id=sa;Password=Your_password123;
    depends_on:
      - ai
    ports:
      - "5034:80"
    restart: unless-stopped

  ui:
    build:
      context: ./WealthWise.UI
    image: wealthwise-ui:local
    ports:
      - "5070:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    driver: bridge
